### ISSUE TITLE
version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by thetoonsofjosh** [wrapper-offline/wrapper-offline#65]
Hello, i'm on linux and i'm trying to run W:Off 2.0.0 beta on there but i keep on getting a error when opening it

A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/thetoonsofjoshagain/wrapper/resources/app/node_modules/sharp/build/Release/sharp-linux-x64.node)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/thetoonsofjoshagain/wrapper/resources/app/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/thetoonsofjoshagain/wrapper/resources/app/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)

it won't let me exit out of wrapper, and the solutions of "GLIBC_2.33 not found" error online don't work on wrapper, can any of you help me so i could wrapper on linux? ok please do

**Comment by 2Epik4u** [comment]
do you have glibc installed

**Comment by 2Epik4u** [comment]
try doing ``npm install --platform=linux --arch=x64 sharp`` in the resources/app folder.

**Comment by thetoonsofjosh** [comment]
I did that and it works, thanks epik, sorry if this message is late
